// <auto-generated />
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewRentalCarManagerAPI.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewRentalCarManagerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310052436_FixUuidDefault")]
    partial class FixUuidDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking", "booking_status", new[] { "pending", "confirmed", "active", "completed", "cancelled", "disputed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking", "promotion_type", new[] { "percentage", "fixed_amount" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "booking", "saga_status", new[] { "started", "succeeded", "failed", "compensating" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fleet", "car_status", new[] { "available", "rented", "maintenance", "inactive" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fleet", "fuel_type", new[] { "gasoline", "diesel", "electric", "hybrid" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fleet", "rental_type", new[] { "hourly", "daily" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fleet", "transmission_type", new[] { "automatic", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "identity", "otp_purpose", new[] { "login", "register", "reset_password", "verify_phone" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "identity", "provider_name", new[] { "google", "facebook", "zalo", "apple" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "identity", "user_status", new[] { "pending", "active", "suspended", "banned" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification", "notif_channel", new[] { "push", "sms", "email", "in_app" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification", "notif_status", new[] { "pending", "sent", "failed", "skipped" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ops", "damage_severity", new[] { "minor", "moderate", "severe" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ops", "damage_status", new[] { "reported", "assessed", "resolved", "disputed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ops", "penalty_status", new[] { "pending", "charged", "disputed", "waived" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ops", "penalty_type", new[] { "traffic_fine", "toll_violation", "late_return", "fuel_shortage", "cleaning_fee" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment", "payment_direction", new[] { "charge", "refund", "payout" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment", "payment_method", new[] { "bank_transfer", "momo", "vnpay", "zalopay", "credit_card" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment", "payment_status", new[] { "pending", "success", "failed", "refunded" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<List<string>>("Scopes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("api_keys_pkey");

                    b.HasIndex(new[] { "KeyHash" }, "api_keys_key_hash_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "api_keys_user_id_idx")
                        .HasFilter("(revoked_at IS NULL)");

                    b.ToTable("api_keys", "identity");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ActualReturnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_return_at");

                    b.Property<int>("BasePriceVnd")
                        .HasColumnType("integer")
                        .HasColumnName("base_price_vnd");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DeliveryFeeVnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("delivery_fee_vnd");

                    b.Property<int>("DepositVnd")
                        .HasColumnType("integer")
                        .HasColumnName("deposit_vnd");

                    b.Property<int>("DiscountVnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("discount_vnd");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PickupLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_location_id");

                    b.Property<Guid>("PricingId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_id");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid")
                        .HasColumnName("promotion_id");

                    b.Property<DateTime>("RentalEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rental_end");

                    b.Property<DateTime>("RentalStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rental_start");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("renter_id");

                    b.Property<Guid>("ReturnLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("return_location_id");

                    b.Property<string>("SagaContext")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("saga_context")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("SagaStep")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("saga_step");

                    b.Property<int>("SurchargeVnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("surcharge_vnd");

                    b.Property<int>("TotalPriceVnd")
                        .HasColumnType("integer")
                        .HasColumnName("total_price_vnd");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("VatVnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("vat_vnd");

                    b.HasKey("Id")
                        .HasName("bookings_pkey");

                    b.HasIndex("PickupLocationId");

                    b.HasIndex("PricingId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("RenterId");

                    b.HasIndex("ReturnLocationId");

                    b.HasIndex(new[] { "CarId", "RentalStart", "RentalEnd" }, "bookings_car_id_rental_start_rental_end_idx");

                    b.ToTable("bookings", "booking");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<List<string>>("Features")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("features")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<bool>("HasIotDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_iot_device");

                    b.Property<List<string>>("ImageUrls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("IotDeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("iot_device_id");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<short>("ManufactureYear")
                        .HasColumnType("smallint")
                        .HasColumnName("manufacture_year");

                    b.Property<int>("MileageKm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mileage_km");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("cars_pkey");

                    b.HasIndex("LocationId");

                    b.HasIndex("ModelId");

                    b.HasIndex("OwnerId");

                    b.HasIndex(new[] { "Features" }, "cars_features_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Features" }, "cars_features_idx"), "gin");

                    b.HasIndex(new[] { "LicensePlate" }, "cars_license_plate_key")
                        .IsUnique();

                    b.ToTable("cars", "fleet");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.CarAvailabilityBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("BlockedFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_from");

                    b.Property<DateTime>("BlockedTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_to");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source")
                        .HasDefaultValueSql("'owner'::character varying");

                    b.HasKey("Id")
                        .HasName("car_availability_blocks_pkey");

                    b.HasIndex(new[] { "CarId", "BlockedFrom", "BlockedTo" }, "car_availability_blocks_car_id_blocked_from_blocked_to_idx");

                    b.ToTable("car_availability_blocks", "fleet");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.CarBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("car_brands_pkey");

                    b.HasIndex(new[] { "Name" }, "car_brands_name_key")
                        .IsUnique();

                    b.ToTable("car_brands", "fleet");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.CarModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("car_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<short>("SeatCount")
                        .HasColumnType("smallint")
                        .HasColumnName("seat_count");

                    b.HasKey("Id")
                        .HasName("car_models_pkey");

                    b.HasIndex(new[] { "BrandId", "Name" }, "car_models_brand_id_name_key")
                        .IsUnique();

                    b.ToTable("car_models", "fleet");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.CarPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<short?>("DurationHours")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_hours");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("PriceVnd")
                        .HasColumnType("integer")
                        .HasColumnName("price_vnd");

                    b.HasKey("Id")
                        .HasName("car_pricing_pkey");

                    b.HasIndex(new[] { "CarId" }, "car_pricing_car_id_idx")
                        .HasFilter("(is_active = true)");

                    b.ToTable("car_pricing", "fleet");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.DamageReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<List<string>>("ImageUrls")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<int?>("RepairCostVnd")
                        .HasColumnType("integer")
                        .HasColumnName("repair_cost_vnd");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.HasKey("Id")
                        .HasName("damage_reports_pkey");

                    b.HasIndex("ReportedBy");

                    b.HasIndex(new[] { "BookingId" }, "damage_reports_booking_id_idx");

                    b.ToTable("damage_reports", "ops");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.ExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProfileData")
                        .HasColumnType("jsonb")
                        .HasColumnName("profile_data");

                    b.Property<string>("ProviderUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_uid");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("external_logins_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("external_logins", "identity");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ward");

                    b.HasKey("Id")
                        .HasName("locations_pkey");

                    b.ToTable("locations", "fleet");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.NotificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMsg")
                        .HasColumnType("text")
                        .HasColumnName("error_msg");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("recipient");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notification_logs_pkey");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "notification_logs_user_id_created_at_idx")
                        .IsDescending(false, true);

                    b.ToTable("notification_logs", "notification");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.OtpToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<short>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("otp_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("otp_tokens_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("otp_tokens", "identity");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.OwnerPayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BankAccount")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bank_account");

                    b.Property<int>("GrossAmountVnd")
                        .HasColumnType("integer")
                        .HasColumnName("gross_amount_vnd");

                    b.Property<int>("NetAmountVnd")
                        .HasColumnType("integer")
                        .HasColumnName("net_amount_vnd");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateOnly>("PeriodFrom")
                        .HasColumnType("date")
                        .HasColumnName("period_from");

                    b.Property<DateOnly>("PeriodTo")
                        .HasColumnType("date")
                        .HasColumnName("period_to");

                    b.Property<int>("PlatformFeeVnd")
                        .HasColumnType("integer")
                        .HasColumnName("platform_fee_vnd");

                    b.HasKey("Id")
                        .HasName("owner_payouts_pkey");

                    b.HasIndex(new[] { "OwnerId", "PeriodFrom", "PeriodTo" }, "owner_payouts_owner_id_period_from_period_to_idx");

                    b.ToTable("owner_payouts", "payment");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Penalty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AmountVnd")
                        .HasColumnType("integer")
                        .HasColumnName("amount_vnd");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("ChargedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("charged_to");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EvidenceUrl")
                        .HasColumnType("text")
                        .HasColumnName("evidence_url");

                    b.HasKey("Id")
                        .HasName("penalties_pkey");

                    b.HasIndex("BookingId");

                    b.HasIndex("ChargedTo");

                    b.ToTable("penalties", "ops");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource");

                    b.HasKey("Id")
                        .HasName("permissions_pkey");

                    b.HasIndex(new[] { "Resource", "Action" }, "permissions_resource_action_key")
                        .IsUnique();

                    b.ToTable("permissions", "identity");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("DiscountValue")
                        .HasColumnType("integer")
                        .HasColumnName("discount_value");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxDiscountVnd")
                        .HasColumnType("integer")
                        .HasColumnName("max_discount_vnd");

                    b.Property<int?>("MinBookingVnd")
                        .HasColumnType("integer")
                        .HasColumnName("min_booking_vnd");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("usage_limit");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("used_count");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("promotions_pkey");

                    b.HasIndex(new[] { "Code" }, "promotions_code_idx")
                        .HasFilter("(is_active = true)");

                    b.HasIndex(new[] { "Code" }, "promotions_code_key")
                        .IsUnique();

                    b.ToTable("promotions", "booking");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("jsonb")
                        .HasColumnName("device_info");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex(new[] { "TokenHash" }, "refresh_tokens_token_hash_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "refresh_tokens_user_id_idx")
                        .HasFilter("(revoked_at IS NULL)");

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewee_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.HasKey("Id")
                        .HasName("reviews_pkey");

                    b.HasIndex("ReviewerId");

                    b.HasIndex(new[] { "BookingId", "ReviewerId" }, "reviews_booking_id_reviewer_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "CarId" }, "reviews_car_id_idx");

                    b.HasIndex(new[] { "RevieweeId" }, "reviews_reviewee_id_idx");

                    b.ToTable("reviews", "ops");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles", "identity");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AmountVnd")
                        .HasColumnType("integer")
                        .HasColumnName("amount_vnd");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GatewayMeta")
                        .HasColumnType("jsonb")
                        .HasColumnName("gateway_meta");

                    b.Property<string>("GatewayTxId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gateway_tx_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("payer_id");

                    b.Property<Guid?>("PayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("payout_id");

                    b.HasKey("Id")
                        .HasName("transactions_pkey");

                    b.HasIndex("PayoutId");

                    b.HasIndex(new[] { "BookingId" }, "transactions_booking_id_idx");

                    b.HasIndex(new[] { "IdempotencyKey" }, "transactions_idempotency_key_key")
                        .IsUnique();

                    b.HasIndex(new[] { "PayerId", "CreatedAt" }, "transactions_payer_id_created_at_idx")
                        .IsDescending(false, true);

                    b.ToTable("transactions", "payment");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("referral_code");

                    b.Property<Guid?>("ReferredById")
                        .HasColumnType("uuid")
                        .HasColumnName("referred_by_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("ReferredById");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "users_phone_idx");

                    b.HasIndex(new[] { "Phone" }, "users_phone_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ReferralCode" }, "users_referral_code_key")
                        .IsUnique();

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("role_permissions_pkey");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", "identity");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.ApiKey", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("api_keys_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Booking", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.Car", "Car")
                        .WithMany("Bookings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_car_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.Location", "PickupLocation")
                        .WithMany("BookingPickupLocations")
                        .HasForeignKey("PickupLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_pickup_location_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.CarPricing", "Pricing")
                        .WithMany("Bookings")
                        .HasForeignKey("PricingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_pricing_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.Promotion", "Promotion")
                        .WithMany("Bookings")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("bookings_promotion_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.User", "Renter")
                        .WithMany("Bookings")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_renter_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.Location", "ReturnLocation")
                        .WithMany("BookingReturnLocations")
                        .HasForeignKey("ReturnLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("bookings_return_location_id_fkey");

                    b.Navigation("Car");

                    b.Navigation("PickupLocation");

                    b.Navigation("Pricing");

                    b.Navigation("Promotion");

                    b.Navigation("Renter");

                    b.Navigation("ReturnLocation");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Car", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.Location", "Location")
                        .WithMany("Cars")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("cars_location_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.CarModel", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("cars_model_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.User", "Owner")
                        .WithMany("Cars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("cars_owner_id_fkey");

                    b.Navigation("Location");

                    b.Navigation("Model");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.CarAvailabilityBlock", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.Car", "Car")
                        .WithMany("CarAvailabilityBlocks")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("car_availability_blocks_car_id_fkey");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.CarModel", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.CarBrand", "Brand")
                        .WithMany("CarModels")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("car_models_brand_id_fkey");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.CarPricing", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.Car", "Car")
                        .WithMany("CarPricings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("car_pricing_car_id_fkey");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.DamageReport", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.Booking", "Booking")
                        .WithMany("DamageReports")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("damage_reports_booking_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.User", "ReportedByNavigation")
                        .WithMany("DamageReports")
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("damage_reports_reported_by_fkey");

                    b.Navigation("Booking");

                    b.Navigation("ReportedByNavigation");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.ExternalLogin", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("external_logins_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.NotificationLog", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.User", "User")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notification_logs_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.OtpToken", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.User", "User")
                        .WithMany("OtpTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("otp_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.OwnerPayout", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.User", "Owner")
                        .WithMany("OwnerPayouts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("owner_payouts_owner_id_fkey");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Penalty", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.Booking", "Booking")
                        .WithMany("Penalties")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("penalties_booking_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.User", "ChargedToNavigation")
                        .WithMany("Penalties")
                        .HasForeignKey("ChargedTo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("penalties_charged_to_fkey");

                    b.Navigation("Booking");

                    b.Navigation("ChargedToNavigation");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Review", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("reviews_booking_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.Car", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("reviews_car_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.User", "Reviewee")
                        .WithMany("ReviewReviewees")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("reviews_reviewee_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.User", "Reviewer")
                        .WithMany("ReviewReviewers")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("reviews_reviewer_id_fkey");

                    b.Navigation("Booking");

                    b.Navigation("Car");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Transaction", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.Booking", "Booking")
                        .WithMany("Transactions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("transactions_booking_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.User", "Payer")
                        .WithMany("Transactions")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("transactions_payer_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.OwnerPayout", "Payout")
                        .WithMany("Transactions")
                        .HasForeignKey("PayoutId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("transactions_payout_id_fkey");

                    b.Navigation("Booking");

                    b.Navigation("Payer");

                    b.Navigation("Payout");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.User", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.User", "ReferredBy")
                        .WithMany("InverseReferredBy")
                        .HasForeignKey("ReferredById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("users_referred_by_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("ReferredBy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("NewRentalCarManagerAPI.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_permission_id_fkey");

                    b.HasOne("NewRentalCarManagerAPI.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_role_id_fkey");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Booking", b =>
                {
                    b.Navigation("DamageReports");

                    b.Navigation("Penalties");

                    b.Navigation("Reviews");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Car", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CarAvailabilityBlocks");

                    b.Navigation("CarPricings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.CarBrand", b =>
                {
                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.CarModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.CarPricing", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Location", b =>
                {
                    b.Navigation("BookingPickupLocations");

                    b.Navigation("BookingReturnLocations");

                    b.Navigation("Cars");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.OwnerPayout", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Promotion", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NewRentalCarManagerAPI.Models.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Bookings");

                    b.Navigation("Cars");

                    b.Navigation("DamageReports");

                    b.Navigation("ExternalLogins");

                    b.Navigation("InverseReferredBy");

                    b.Navigation("NotificationLogs");

                    b.Navigation("OtpTokens");

                    b.Navigation("OwnerPayouts");

                    b.Navigation("Penalties");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewReviewees");

                    b.Navigation("ReviewReviewers");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
